function hip_rom = evaluateHipROM_fixedBaseline(X)

% Commented out below as this should be made automatic!
%fprintf('\nApply torque pattern generated by magnitude = %i, rise = %i, peak = %i, fall = %i.\n', X.force, X.rise, X.peak, X.fall);

% The below should be automatic as well, though there will likely need to be some detection of when the file is ready!
str = input('Input name of TRC file produced.\n');

% So basically, from here, I will assume that a .TRC file has been generated with the name trc_file. 
save_dir = ...
    ['hiprom-' 'rise' num2str(X.rise) 'peak' num2str(X.peak) 'fall' num2str(X.fall)];
segmentTRC(str, save_dir);

markers = dir([save_dir filesep '*.trc']);
vals = zeros(length(markers), 1);
for i=1:length(markers)
    ost = OpenSimTrial(X.model, [save_dir filesep markers(i).name], 'temp-ost-results');
    ost.run('IK');
    ik = Data(['temp-ost-results' filesep 'IK' filesep 'ik.mot']);
    hip = ik.getColumn('hip_flexion_r');
    vals(i) = abs(X.baseline - abs(max(hip) - min(hip)));
end

hip_rom = mean(vals);

end
    
        
    