function paths = constructPaths(settings, dirs, iteration)
% Construct the mid-level strings & paths for the policy controller.
    
    % Marker & grf file names.
    paths.strings.markers = ...
        [settings.v_name sprintf(settings.v_format, iteration)];
    paths.strings.grfs = ...
        [settings.d_name sprintf(settings.d_format, iteration)];
    
    % Raw marker & grf files.
    paths.files.markers = ...
        [settings.base_dir filesep paths.strings.markers '.trc'];
    paths.files.grfs = ...
        [settings.base_dir filesep paths.strings.grfs '.txt'];
            
    % Inner-level directories for saving segmentation & OpenSim results. 
    paths.directories.segmented_inner_grf = ...
        [dirs.segmented filesep 'grf_iteration' sprintf('%03i', iteration)];
    paths.directories.segmented_inner_markers = ...
        [dirs.segmented filesep 'markers_iteration' sprintf('%03i', iteration)];
    paths.directories.opensim_inner = ...
        [dirs.opensim filesep 'iteration' sprintf('%03i', iteration)];
end