function hip_rom = evaluateHipROM(X)

scaled_model = 'chris_scaled.osim';

baseline = 49.7;

apo_controller_frequency = 100;
gait_cycle_length = 1.0596;
peak_force = 5;
n_points = round(apo_controller_frequency*gait_cycle_length);

fprintf('\nApply torque pattern generated by frames = %i, magnitude = %i, rise = %i, peak = %i, fall = %i.\n', n_points, peak_force, X.rise, X.peak, X.fall);

str = input('Input name of TRC file produced.\n');

save_dir = ...
    ['hiprom-' 'rise' num2str(X.rise) 'peak' num2str(X.peak) 'fall' num2str(X.fall)];
segmentTRC(str, save_dir);

markers = dir([save_dir filesep '*.trc']);
vals = zeros(length(markers), 1);
for i=1:length(markers)
    ost = OpenSimTrial(scaled_model, [save_dir filesep markers(i).name], 'temp-ost-results');
    ost.run('IK');
    ik = Data(['temp-ost-results' filesep 'IK' filesep 'ik.mot']);
    hip = ik.getColumn('hip_flexion_r');
    vals(i) = abs(baseline - abs(max(hip) - min(hip)));
end

hip_rom = mean(vals);

end
    
        
    