function CoP_ML_disp = evaluateCoP_ML_disp(X)

apo_controller_frequency = 100;
gait_cycle_length = 1.0596;
peak_force = 5;
n_points = round(apo_controller_frequency*gait_cycle_length);

fprintf('\nApply torque pattern generated by rise = %i, peak = %i, fall = %i.\n', X.rise, X.peak, X.fall);

x = generateAssistiveProfile(n_points, peak_force, X.rise, X.peak, X.fall);
id = fopen('test.txt', 'w');
for i=1:length(x)
    fprintf(id, '%.5f\t', x(i));
end
fclose(id);

fprintf('\nTorque pattern generated and saved in test.txt.');

str = input('Input name of GRF file produced.\n');

save_dir = ...
    ['rise' num2str(X.rise) 'peak' num2str(X.peak) 'fall' num2str(X.fall)];
produced_mot = [save_dir '.mot'];
produceMOT(str, produced_mot);
segmentMOT(produced_mot, save_dir);

grfs = dir(save_dir);
vals = zeros(length(grfs), 1);
for i=3:length(grfs)
    grf_data = Data([save_dir filesep grfs(i).name]);
    cop_ml = grf_data.getColumn('ground_force1_pz');
    vals(i) = abs(max(cop_ml) - min(cop_ml));
end

CoP_ML_disp = mean(vals);

end